enum ActionTypes {
  HYDRATE_AUTH = 'HYDRATE_AUTH',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  HIDE_LOGIN_FAILED = 'HIDE_LOGIN_FAILED',
  SIGN_UP_FAILED = 'SIGN_UP_FAILED',
  HIDE_SIGN_UP_FAILED = 'HIDE_SIGN_UP_FAILED',

  HYDRATE_CHATS = 'HYDRATE_CHATS',
  LOAD_MESSAGES = 'LOAD_MESSAGES',
  FETCH_CHAT = 'FETCH_CHAT',
  NEW_MESSAGE = 'NEW_MESSAGE',
  READ_MESSAGE = 'READ_MESSAGE',
  NEW_CHAT = 'NEW_CHAT',
  NEW_TODO = 'NEW_TODO',
  EDIT_TODO = 'EDIT_TODO'
}

export default ActionTypes
